Initial commit download functionality
joelekstrom/fastmate pull request #82
Opened 2022-06-08 19:13 UTC by mdbraber

Initial commit for adding in-app download functionality. @joelekstrom there's a few settings that should be user-configurable (selecting download-directory and auto-opening extensions). Could you take a look at how to integrate those in the settings window? I've added a `FIXME` statement in places to check.

2022-06-08 21:08 UTC, joelekstrom requested changes
Thanks for the PR! Much appreciated

2022-06-08 21:08 UTC, joelekstrom commented on Fastmate/WebViewController.m
> +- (void)downloadFileFromURL:(NSURL *)url completion:(void (^)(NSString *filepath))completion {
I assume the completion block could be removed since it's not used?

2022-06-09 14:47 UTC, mdbraber commented on Fastmate/WebViewController.m
> +        if (shouldDownload || ![components.path.lastPathComponent hasSuffix:@".pdf"]) {
Done

2022-06-10 08:39 UTC, joelekstrom commented on Fastmate/WebViewController.m
> +- (NSString *)nextAvailableFilenameAtPath:(NSString *)aPath proposedFilename:(NSString *)aName{
Just a thought - could an alternative be to have a "fake" `.part` file being updated with `NSProgress`, and then replacing it with the real file from the temp location on finish?

2022-06-10 12:06 UTC, mdbraber commented
@joelekstrom got it to work - see changes in the PR. Can you help check and also take a look at ideas for integrating this in the settings. Or do we not need to make any of this configurable (download location, auto-open)?

2022-06-10 12:21 UTC, joelekstrom commented
@mdbraber I think as a first step it's good enough without settings - of course a setting would be nice but that could be another PR 👍

2022-06-10 12:33 UTC, mdbraber commented
LGTM

2022-06-10 12:33 UTC, joelekstrom requested changes
Looks much better, with a few notes!

2022-06-10 12:33 UTC, joelekstrom commented on Fastmate/DownloadFileManager.m
> ++ (BOOL)createDirection:(NSString *)directPath {
`createDirectory` and try to avoid shorted variable names, would prefer `directoryPath` or just `path`

2022-06-10 12:33 UTC, joelekstrom commented on Fastmate/DownloadManager.h
> +@interface DownloadManager : NSObject
Since this seems more like download task (it only handles a single task at once right?) I feel like it should not be called a manager since it's more expected to be a singleton then. Perhaps call it `FileDownloadTask` or similar instead?

2022-06-10 12:33 UTC, joelekstrom commented on Fastmate/DownloadManager.m
> +    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
`NSURLSessionDataTask` will dispatch internally so should not be needed

2022-06-10 12:33 UTC, joelekstrom commented on Fastmate/DownloadManager.m
> +        // FIXME: not sure what's the way to go here... re-download directly?
I think presenting a `Download failed` alert is the correct thing to do, with the reason if possible so we can debug it if it becomes a commonly reported error

2022-06-10 12:33 UTC, joelekstrom commented on Fastmate/DownloadManager.m
> +    if (error == nil) {
prefer early exits like

```objc
if (error) {
    NSLog([NSString stringWithFormat:@"Something went wrong: %@", error]);
    return;
}

2022-06-10 12:33 UTC, joelekstrom commented on Fastmate/DownloadManager.m
> +    }
I think the URLSession needs to be invalidated somewhere in this function, or there's a memory leak since a new one is created for each download. See discussion here: https://developer.apple.com/documentation/foundation/urlsession/1411530-delegate

2022-06-10 13:22 UTC, joelekstrom commented on Fastmate/DownloadManager.m
> +    }
Bump on this comment, maybe I missed it but seems like there's no invalidation of the session?

2022-06-13 12:43 UTC, joelekstrom commented on Fastmate/FileDownloadTask.m
> +        [self downloadWithURL:dataTask.originalRequest.URL];
Do you think this is safe to do? If something is weird with the download I imagine it can get stuck in an endless download loop 😅

2022-06-13 12:43 UTC, joelekstrom commented on Fastmate/FileDownloadTask.m
> +    self.outStream = [NSOutputStream outputStreamToFileAtPath:self.downloadingPath append:YES];
Is it correct to create a new outStream here? It overwrites the one created in `downloadWithURL`.

2022-06-13 12:43 UTC, joelekstrom commented on Fastmate/FileDownloadTask.m
> +        return;
Does this need to call `[self clean]` or is that handled by the cancellationHandler below?

2022-06-13 16:33 UTC, mdbraber commented
@joelekstrom I've created a final update to include download related settings and to use a FileDownloadManager to detect already running downloaded processes. Should be the last update before we can hopefully finish this. I might have don't some illogical things as I'm still rather inexperienced coding in Obj-C :-) Thanks for your feedback so far.

2022-06-15 19:24 UTC, joelekstrom commented
@mdbraber Great job! I've looked through the code and will come back with some suggestions, but all in all this seems like a real nice solution to me.

But one confusion - when I'm trying this locally I can clearly see the .fmdownload file, but I can't see any progress indicator on it in finder/dock or on my downloads folder. Do you see the actual progress locally?

2022-06-16 06:14 UTC, joelekstrom commented
Hmm, no that still doesn't help for me. I will investigate a bit more when I get the time. I also think we can use the `NSURLSessionDownloadTask` to slim it down a bit, still just creating a tempt file at target location. I will experiment a bit and see if I can get it to work!

2022-06-16 06:43 UTC, mdbraber commented
I've considered using NSURLSessionDownloadTask as it would be the likely designated class for this. My consideration is that a temporary file is created in a cache location and the progress of the download (e.g. byte size of the file) can't be seen if we create an empty .fmdownload file. I opted for streaming of the output, rather than 0-byte temp file.

2022-06-16 08:05 UTC, mdbraber commented
@joelekstrom here's a small POC I've created to test the progress indicator:

```
#import <Foundation/Foundation.h>

int main(int argc, char** argv) {
	NSString *_downloadingPath = @"/Users/mdbraber/Downloads/test.pdf";
	NSDictionary *info = [NSDictionary dictionaryWithObjectsAndKeys:
		@"NSProgressFileOperationKindDownloading", @"NSProgressFileOperationKindKey",
		[NSURL fileURLWithPath:_downloadingPath], @"NSProgressFileURLKey",
		nil];
	NSProgress *progress = [[NSProgress alloc] initWithParent:nil userInfo:info];
	self.progress = progress;
	[self.progress setKind:@"NSProgressKindFile"];
	[self.progress setPausable:NO];
	[self.progress setCancellable:YES];
    [self.progress setTotalUnitCount:10];
	int self.count = 0;
	double delayInSeconds = 2.0;
	NSLog(@"Starting timer");
	[self performSelector:@selector(updateCount:) afterDelay:2.0];
}

void updateCount(count) {
	[self.progress setCurrentCount:self.count];
}
```

2022-06-16 11:47 UTC, joelekstrom commented
Interesting that I don't see it, must be something with my setup 🤔 will try a bit more. You can get progress from URLSessionDownloadTask using `URLSessionDownloadDelegate`: https://developer.apple.com/documentation/foundation/urlsessiondownloaddelegate/1409408-urlsession

I was thinking there's still a tmp .fmdownload file created where we post the progress, but then you don't need to handle the download buffering etc

2022-06-16 12:59 UTC, mdbraber commented
Sorry @joelekstrom I accidentally posted the wrong POC - I've edited the comment above with the right POC and instructions (copied from https://gist.github.com/torarnv/0a4b6b4509bad7682b2dc0c561ec4437). Wondering if this POC would work for you. Main things I found that prevent the progress bar from showing are (1) fileURL paths with symlinked locations (2) forgetting to use `publish`

Regarding `NSURLSessionDownloadTask` I agree it means not having to handle download buffering, but the file size wouldn't be reflected in the Finder. I've take a cue from Safari to see how they do it, and there the file is streamed directly to a download location (actually it's a bit different, the Safari .download file is actually a package file which holds the temporary file) Of course I think it's fine if you would prefer to switch to `NSURLSessionDownloadTask` but I think personally I prefer this approach.

2022-06-16 13:54 UTC, joelekstrom commented
All right, sounds good let's keep this approach! 👍 I'll try to test the POC if I get some time layer today

2022-06-17 20:05 UTC, joelekstrom commented
Interestingly, I do see the progress bar when running the POC, but not in Fastmate. Gonna have to try a bit more 🤔

2022-06-17 20:30 UTC, joelekstrom commented
So strange, I got it to work _once_ in Fastmate but then it stopped. I think something is acting up. Will debug a bit more tomorrow.

Btw, you can set up the progress object a bit more nicely this way:
```swift
    self.progress = [NSProgress progressWithTotalUnitCount:_totalBytes];
    self.progress.fileOperationKind = NSProgressFileOperationKindDownloading;
    self.progress.fileURL = [[NSURL fileURLWithPath:self.downloadingPath] URLByResolvingSymlinksInPath];
    self.progress.kind = NSProgressKindFile;
    self.progress.pausable = NO;
    self.progress.cancellable = YES;
```

2022-06-21 04:34 UTC, mdbraber commented
Thanks for the update @joelekstrom, update the initialization. Any update on getting the progress bar to work on your side?

2022-06-21 09:16 UTC, joelekstrom commented
Been a bit busy lately so haven't spent much time on it! However, if we can't get this to work perfectly that's fine. We could also ship it as a preference disabled by default to allow people to beta test it. Let people opt in to this new download experience and see how it goes. It might just be my computer acting up 😄

2022-06-21 14:58 UTC, mdbraber commented
We could make the whole download  functionality optional, I would than suggest switching it on by default qn making it possible to revert to the current behavior

2022-06-26 06:49 UTC, joelekstrom commented
Yep, that sounds good to me! Would you like to add a preference for it? (Sorry for being so slow btw)

2022-06-26 17:38 UTC, mdbraber commented
@joelekstrom yes, I'll add a preference for the download behavior in general, so people can toggle it on/off. No problem about the response time, I can relate :-) Would be nice to ship a version in the coming days / weeks, especially to get some feedback from people what can be improved.

2022-06-26 21:46 UTC, joelekstrom commented
I agree! Would also be nice to ship the other patches you’ve made

2022-08-02 07:23 UTC, joelekstrom commented
Hi @mdbraber! I feel like it's time we get this out. I rebased the branch added some minor changes including a setting to fall back to legacy downloads. Any thoughts on those? Otherwise I'll merge it and ship a new update soon. Thanks again for all the work on this!

2022-08-07 19:42 UTC, merged

2022-08-19 09:26 UTC, mdbraber commented
@joelekstrom sorry for the delayed reply I was away for a bit. Thanks for merging this and adding a setting to revert to the legacy behavior. I think only one small detail to check now with users is if we can get the progress bar to show. It still shows on my install, but I've heard from at least one other user it (also, like with you) doesn't show up. Any ideas how we could get some user feedback on that?

2022-08-19 10:50 UTC, joelekstrom commented
@mdbraber no problem! It does show on my new computer so it may have been something with my setup on the previous one